### PR TITLE
Patchserver repeatable one shot setup

### PR DESCRIPTION
**Pull request by chhex**
This pull try's to resolve the Idempotenz goal of the Puppet plans for Setting up the Piper Machine.. Essentially meaning that can run the plan more then once and they shouldn't fail and they should produce the same result , given that the Puppet code hasn't changed and it's parametrization. 

I believe this is achieved at least nearly... See also open Issues. 

This pull request also incorporates @apgsga-uge  Feedback with the  https://github.com/apgsga-it/patchserver-setup/commit/96868628f8a7bd734365f4defdfb825f1adae384 commit. 

I have split the jenkins plan into three different plans: 

- site-modules/piper/plans/jenkins_account_create.pp # creates to Jenkins user account with a default Password , see https://github.com/apgsga-it/patchserver-setup/blob/64707e06810442e6dbbd288d4de835ab4b2c80fa/site-modules/piper/plans/jenkins_account_create.pp

- site-modules/piper/plans/jenkins_dirs_create.pp  # Creates the necessary directories and files for the Jenkins Installation , see https://github.com/apgsga-it/patchserver-setup/blob/64707e06810442e6dbbd288d4de835ab4b2c80fa/site-modules/piper/plans/jenkins_dirs_create.pp

- site-modules/piper/plans/jenkins_service_install.pp # Jenkins installation it self, see https://github.com/apgsga-it/patchserver-setup/blob/64707e06810442e6dbbd288d4de835ab4b2c80fa/site-modules/piper/plans/jenkins_service_install.pp

**Open points**

-  The copying   of the our gradle home, which is done with rsync and avoids overwriting existing directories and file can still have side effects, when we add new files or directories at a root directory level. TO BE DISCUSSED 
- The ruby install script , see https://github.com/apgsga-it/patchserver-setup/blob/master/install.rb does not honor installation ordering of the plans.

### CODE REVIEW

**Comment by chhex** [comment]
The Open Point : 

- The ruby install script , see  does not honor ordering of the plans. 
has been resolved see https://github.com/apgsga-it/patchserver-setup/pull/5/commits/139a91418564183df17cf6559a98381392b37e5f

**Review by apgsga-jhe — APPROVED** [review]
@chhex , @apgsga-uge : looking good to me.
Regarding "Gradle Home" open point: when we first copy the folder, we copy everything, including the ".git" information. That mean, we end with a folder which is under version control, on the same branch as what's been checkout locally before calling bolt plans. In context of a re-install, couldn't we do a "git fetch" and "git pull" for this part?

**Comment by chhex** [comment]
> @chhex , @apgsga-uge : looking good to me.
> Regarding "Gradle Home" open point: when we first copy the folder, we copy everything, including the ".git" information. That mean, we end with a folder which is under version control, on the same branch as what's been checkout locally before calling bolt plans. In context of a re-install, couldn't we do a "git fetch" and "git pull" for this part?
@apgsga-jhe 
Very good point. The git information is actually currently not included: 

`rsync -P -r --ignore-existing --include=*/ --exclude=.git* ${temp_dir}/gradlehome/* ${targetall.vars[gradle_home]}/home`

What is done: 
1. git clone on the client machine 
2. bolt upload to target machine into a temp directory 
3. the above rsync to to target directory 

Ratio: Assumption that we don't want the gradle home version controlled in the installation....

But, yes there also argument for pulling directory. 

Shall i change? 

@apgsga-uge fyi

**Comment by chhex** [comment]
@apgsga-jhe  @apgsga-uge  With the commit https://github.com/apgsga-it/patchserver-setup/commit/2573ba106acf8f80bf571d6faa533eb2651e4ff2
additionally the creation of a initial Jenkins Admin user with the necessary authorized rsa keys setup is automated

Basically the whole setup can now be done completely without manually steps 👍 
`bolt plan run piper::cvs_install   --concurrency 10 -t testvms
bolt plan run piper::git_install   --concurrency 10 -t testvms
bolt plan run piper::wget_install   --concurrency 10 -t testvms
bolt plan run piper::java_install   --concurrency 10 -t testvms
bolt plan run piper::gradle_install   --concurrency 10 -t testvms
bolt plan run piper::maven_install   --concurrency 10 -t testvms
bolt plan run piper::jenkins_account_create   --concurrency 10 -t testvms
bolt plan run piper::jenkins_dirs_create   --concurrency 10 -t testvms
bolt plan run piper::jenkins_service_install   --concurrency 10 -t testvms
bolt plan run piper::jenkins_create_jobs   --concurrency 10 -t testvms
bolt plan run piper::yum_repo   --concurrency 10 -t testvms
bolt plan run piper::piper_install   --concurrency 10 -t testvms
bolt plan run piper::piper_properties   --concurrency 10 -t testvms`

To effectively be able to build jobs the following manual step needs to be done:

`su - jenkins `
`ssh-copy-id <user>@cvs-t.apgsga.ch #copy the key using your id`

To use piper the steps 3. - 7. described in the README under Configure Piper need to be done manually. 

Open Points: 

1.  Currently the sudo user of the local target is used as initial local Jenkins Admin User plus his password. This needs to be reconsidered. I suggest with a separate Ticket and after a end to end review of the process. 
2.  Further automated the Piper Configuration Process, so that in the end only the ssh-copy-id to the cvs server is left. 
3. Adopt README

Note: 
Any Reveiws or walkthroughs should be done with this pull request , when the pull request is merged

**Comment by apgsga-jhe** [comment]
> > @chhex , @apgsga-uge : looking good to me.
> > Regarding "Gradle Home" open point: when we first copy the folder, we copy everything, including the ".git" information. That mean, we end with a folder which is under version control, on the same branch as what's been checkout locally before calling bolt plans. In context of a re-install, couldn't we do a "git fetch" and "git pull" for this part?
> > @apgsga-jhe
> > Very good point. The git information is actually currently not included:
> 
> `rsync -P -r --ignore-existing --include=*/ --exclude=.git* ${temp_dir}/gradlehome/* ${targetall.vars[gradle_home]}/home`
> 
> What is done:
> 
> 1. git clone on the client machine
> 2. bolt upload to target machine into a temp directory
> 3. the above rsync to to target directory
> 
> Ratio: Assumption that we don't want the gradle home version controlled in the installation....
> 
> But, yes there also argument for pulling directory.
> 
> Shall i change?
> 
> @apgsga-uge fyi

@chhex : I think I would change it , yes. I believe it will be easier to track changes on our Gradle home, and to keep the source up to date and centralized.
@apgsga-uge : FYI

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe @apgsga-uge With the commit [2573ba1](https://github.com/apgsga-it/patchserver-setup/commit/2573ba106acf8f80bf571d6faa533eb2651e4ff2)
> additionally the creation of a initial Jenkins Admin user with the necessary authorized rsa keys setup is automated
> 
> Basically the whole setup can now be done completely without manually steps:
> 
> ```
> bolt plan run piper::cvs_install   --concurrency 10 -t testvms
> bolt plan run piper::git_install   --concurrency 10 -t testvms
> bolt plan run piper::wget_install   --concurrency 10 -t testvms
> bolt plan run piper::java_install   --concurrency 10 -t testvm
> bolt plan run piper::gradle_install   --concurrency 10 -t testvms
> bolt plan run piper::maven_install   --concurrency 10 -t testvms
> bolt plan run piper::jenkins_account_create   --concurrency 10 -t testvms
> bolt plan run piper::jenkins_dirs_create   --concurrency 10 -t testvms
> bolt plan run piper::jenkins_service_install   --concurrency 10 -t testvms
> bolt plan run piper::jenkins_create_jobs   --concurrency 10 -t testvms
> bolt plan run piper::yum_repo   --concurrency 10 -t testvms
> bolt plan run piper::piper_install   --concurrency 10 -t testvms
> bolt plan run piper::piper_properties   --concurrency 10 -t testvms
> ```
> 
> To effectively be able to **run the build jobs** on jenkins the following manual step needs to be done:
> 
> `su - jenkins `
> `ssh-copy-id <user>@cvs-t.apgsga.ch #copy the key using your id`
> 
> To use **piper** the steps 3. - 7. described in the README under Configure Piper need to be done manually.
> 
> **Open Points:**
> 
> 1. Currently the sudo user of the local target is used as initial local Jenkins Admin User plus his password. This needs to be reconsidered. I suggest with a separate Ticket and after a end to end review of the process.
> 2. Further automated the Piper Configuration Process, so that in the end only the ssh-copy-id to the cvs server is left.
> 3. Adopt README
> 
> **Note:**
> Any Reveiws or walkthroughs should be done with this pull request , when the pull request is merged

@chhex : On Monday, Ueli and I have planed some time in order to setup the test environment on Ueli's machine. Maybe it will be the perfect opportunity to test? Either you can merge this one today, or on Monday we can do the setup from your branch.

@apgsga-uge : FYI

**Comment by chhex** [comment]
> > @apgsga-jhe @apgsga-uge With the commit [2573ba1](https://github.com/apgsga-it/patchserver-setup/commit/2573ba106acf8f80bf571d6faa533eb2651e4ff2)
> > additionally the creation of a initial Jenkins Admin user with the necessary authorized rsa keys setup is automated
> > Basically the whole setup can now be done completely without manually steps:
> > ```
> > bolt plan run piper::cvs_install   --concurrency 10 -t testvms
> > bolt plan run piper::git_install   --concurrency 10 -t testvms
> > bolt plan run piper::wget_install   --concurrency 10 -t testvms
> > bolt plan run piper::java_install   --concurrency 10 -t testvm
> > bolt plan run piper::gradle_install   --concurrency 10 -t testvms
> > bolt plan run piper::maven_install   --concurrency 10 -t testvms
> > bolt plan run piper::jenkins_account_create   --concurrency 10 -t testvms
> > bolt plan run piper::jenkins_dirs_create   --concurrency 10 -t testvms
> > bolt plan run piper::jenkins_service_install   --concurrency 10 -t testvms
> > bolt plan run piper::jenkins_create_jobs   --concurrency 10 -t testvms
> > bolt plan run piper::yum_repo   --concurrency 10 -t testvms
> > bolt plan run piper::piper_install   --concurrency 10 -t testvms
> > bolt plan run piper::piper_properties   --concurrency 10 -t testvms
> > ```
> > 
> > 
> > To effectively be able to **run the build jobs** on jenkins the following manual step needs to be done:
> > `su - jenkins `
> > `ssh-copy-id <user>@cvs-t.apgsga.ch #copy the key using your id`
> > To use **piper** the steps 3. - 7. described in the README under Configure Piper need to be done manually.
> > **Open Points:**
> > 
> > 1. Currently the sudo user of the local target is used as initial local Jenkins Admin User plus his password. This needs to be reconsidered. I suggest with a separate Ticket and after a end to end review of the process.
> > 2. Further automated the Piper Configuration Process, so that in the end only the ssh-copy-id to the cvs server is left.
> > 3. Adopt README
> > 
> > **Note:**
> > Any Reveiws or walkthroughs should be done with this pull request , when the pull request is merged
> 
> @chhex : On Monday, Ueli and I have planed some time in order to setup the test environment on Ueli's machine. Maybe it will be the perfect opportunity to test? Either you can merge this one today, or on Monday we can do the setup from your branch.
> 
> @apgsga-uge : FYI

@apgsga-jhe Sounds great. I would suggest, that i merge this pull before then.  So you guys have the whole picture and do the review based on the master branch. Also i will adopt the README to reflect the current state as top priority of the open points (...before missing functionality). What do you think? 

@apgsga-uge FYI

**Comment by apgsga-jhe** [comment]
> > > @apgsga-jhe @apgsga-uge With the commit [2573ba1](https://github.com/apgsga-it/patchserver-setup/commit/2573ba106acf8f80bf571d6faa533eb2651e4ff2)
> > > additionally the creation of a initial Jenkins Admin user with the necessary authorized rsa keys setup is automated
> > > Basically the whole setup can now be done completely without manually steps:
> > > ```
> > > bolt plan run piper::cvs_install   --concurrency 10 -t testvms
> > > bolt plan run piper::git_install   --concurrency 10 -t testvms
> > > bolt plan run piper::wget_install   --concurrency 10 -t testvms
> > > bolt plan run piper::java_install   --concurrency 10 -t testvm
> > > bolt plan run piper::gradle_install   --concurrency 10 -t testvms
> > > bolt plan run piper::maven_install   --concurrency 10 -t testvms
> > > bolt plan run piper::jenkins_account_create   --concurrency 10 -t testvms
> > > bolt plan run piper::jenkins_dirs_create   --concurrency 10 -t testvms
> > > bolt plan run piper::jenkins_service_install   --concurrency 10 -t testvms
> > > bolt plan run piper::jenkins_create_jobs   --concurrency 10 -t testvms
> > > bolt plan run piper::yum_repo   --concurrency 10 -t testvms
> > > bolt plan run piper::piper_install   --concurrency 10 -t testvms
> > > bolt plan run piper::piper_properties   --concurrency 10 -t testvms
> > > ```
> > > 
> > > 
> > > To effectively be able to **run the build jobs** on jenkins the following manual step needs to be done:
> > > `su - jenkins `
> > > `ssh-copy-id <user>@cvs-t.apgsga.ch #copy the key using your id`
> > > To use **piper** the steps 3. - 7. described in the README under Configure Piper need to be done manually.
> > > **Open Points:**
> > > 
> > > 1. Currently the sudo user of the local target is used as initial local Jenkins Admin User plus his password. This needs to be reconsidered. I suggest with a separate Ticket and after a end to end review of the process.
> > > 2. Further automated the Piper Configuration Process, so that in the end only the ssh-copy-id to the cvs server is left.
> > > 3. Adopt README
> > > 
> > > **Note:**
> > > Any Reveiws or walkthroughs should be done with this pull request , when the pull request is merged
> > 
> > 
> > @chhex : On Monday, Ueli and I have planed some time in order to setup the test environment on Ueli's machine. Maybe it will be the perfect opportunity to test? Either you can merge this one today, or on Monday we can do the setup from your branch.
> > @apgsga-uge : FYI
> 
> @apgsga-jhe Sounds great. I would suggest, that i merge this pull before then. So you guys have the whole picture and do the review based on the master branch. Also i will adopt the README to reflect the current state as top priority of the open points (...before missing functionality). What do you think?
> 
> @apgsga-uge FYI

@chhex : Sounds perfect to me !! 
@apgsga-uge : FYI

**Comment by chhex** [comment]
@apgsga-jhe  @apgsga-uge  This is now reviewable. But as discussed with @apgsga-jhe  i will merge, but keep this pull as reference

**Pull request merged**
